### ISSUE TITLE
editWorkflowSettings

### ISSUE THREAD

**Issue by elwingert** [kuklaph/cascade-cms-api#2]
Great library, this has been extremely useful!

We are attempting to edit the workflow settings of a folder and have been unable to.

Have you had any luck with calling the editWorkflowSettings method?  Hoping for any insight you'd have.

    const workflowSettings = await cascadeAPI.readWorkflowSettings({
      identifier: {
        type: "folder",
        path: {
          siteId: site.id,
          path: "/",
        },
      },
    });
    console.log("Settings before: ", workflowSettings);

which the readWorkflowSettings gets a valid response, and reading the swagger docs I'd assume I'd then be able to call it right back with the following:

      await cascadeAPI.editWorkflowSettings({
        workflowSettings: workflowSettings.workflowSettings,
        applyInheritWorkflowsToChildren: true,
        applyRequireWorkflowToChildren: true,
      });

but it fails with an 'undefined' error.  Once we can get past this simple test, I'm hoping to then make the additional adjustments we'd like.

Thanks!

**Comment by kuklaph** [comment]
Hi @elwingert - I'm going to do some testing and will get back to you

**Comment by kuklaph** [comment]
@elwingert I can't get it to work either. I tried both with the library as well as a standalone http client (Bruno). I'm in contact with HH and they are looking into it. Not sure if it's an API limitation or a bug, but once I know more, I'll let you know.

**Comment by kuklaph** [comment]
@elwingert Okay so it turns out that there is a discrepancy between the SOAP and REST API. Apparently the REST implementation expects the `identifier` to be at the top level.. `editAccessRights` is another endpoint that has this "issue". It also means that we can't simply feed the read response back into the edit response like we can with other endpoints because for whatever reason they've decided to include the `identifier` object nested in the `workflowSettings` response. I've requested that they change the responses to move the `identifier` to the top level for these two endpoints... but who knows if they will do that. I will need to make adjustments for this in the library. Just for context, these are what we found to work:

- You can add `/folder/{id}` to `/editWorkflowSettings` and it works: `/editWorkflowSettings/folder/{id}`
- Move the `identifier` object outside of the `workflowSettings` object:
```javascript
{
  "identifier": {
    "id": "id",
    "path": {
      "path": "_dev/test",
      "siteId": "id",
      "siteName": "Staging"
    },
    "type": "folder",
    "recycled": false
  },
  "workflowSettings": {
    "workflowDefinitions": [],
    "inheritedWorkflowDefinitions": [],
    "inheritWorkflows": false,
    "requireWorkflow": false
  }
}
```
Or similar to your example:
```javascript
  const identifier = {
    type: "folder",
    id: "",
  };
  const readWorkflowSettings = await cascadeAPI.readWorkflowSettings({
    identifier,
  });
  console.log(JSON.stringify(readWorkflowSettings.workflowSettings, null, 2));

  const result = await cascadeAPI.editWorkflowSettings({
    identifier,
    workflowSettings: readWorkflowSettings.workflowSettings,
    applyInheritWorkflowsToChildren: false,
    applyRequireWorkflowToChildren: false,
  });

  console.log(result);
```

**Comment by elwingert** [comment]
Thanks @kuklaph for all of your help with this one and tracking down the "issue", very much appreciated!  We'll give the temporary solution a try and await your adjustment (i can't call it a fix, as it doesn't seem like anything wrong with what you've done) to the library as well.

**Comment by kuklaph** [comment]
@elwingert No problem, glad it got figured out and thanks for pointing it out. `1.0.6` has been pushed here as well as npm. You should now see the `identifier` param outside at the top-level object as a required parameter for both `editWorkflowSettings` and `editAccessRights` endpoints. Going to close this, but feel free to let me know if you find anything else.
